import { NotificationType, OrderStatus, ProductBadge, UserRole } from '../constants/enums';
import { mockImage } from '../constants/mockImages';
import type {
  Address,
  CheckoutLineItem,
  CheckoutSummary,
  DeliveryAssignment,
  DeliveryPartner,
  DeliverySlot,
  Notification,
  Order,
  Product,
  Store,
  User,
  VendorProduct,
} from '../types';

export const MOCK_USER: User = {
  id: 'u1',
  name: 'Alex Rivers',
  email: 'alex.rivers@freshdash.com',
  phone: '+1234567890',
  role: UserRole.User,
  avatarUrl: 'https://i.pravatar.cc/150?u=alexrivers',
};

export const MOCK_CHECKOUT_ADDRESS: Address = {
  id: 'a-checkout',
  label: 'Home',
  line1: '452, Silicon Valley Residency Block B, 4th Floor',
  line2: 'Electronic City Phase 1, Bangalore, Karnataka - 560100',
  city: 'Bangalore',
  state: 'Karnataka',
  zipCode: '560100',
  isDefault: true,
};

export const MOCK_DELIVERY_SLOTS: DeliverySlot[] = [
  { id: 'express', label: 'Today', sublabel: '15 - 20 Mins', isExpress: true },
  { id: 'slot1', label: 'Today', sublabel: '04:00 PM - 06:00 PM' },
  { id: 'slot2', label: 'Today', sublabel: '06:00 PM - 08:00 PM' },
  { id: 'slot3', label: 'Tomorrow', sublabel: '08:00 AM - 10:00 AM' },
];

export const MOCK_CHECKOUT_ITEMS: CheckoutLineItem[] = [
  {
    id: 'ci1',
    name: 'Organic Haas Avocados Pack of 2',
    imageUrl: mockImage('ci1'),
    price: 249,
  },
  {
    id: 'ci2',
    name: 'Fresh Strawberries 250g Box',
    imageUrl: mockImage('ci2'),
    price: 180,
  },
  {
    id: 'ci3',
    name: 'Farm Fresh Milk 1 Litre',
    imageUrl: mockImage('ci3'),
    price: 75,
  },
];

export const MOCK_CHECKOUT_SUMMARY: CheckoutSummary = {
  itemTotal: 504,
  deliveryFee: 0,
  deliveryFeeStrikethrough: 40,
  taxes: 22.5,
  discount: 0,
  total: 526.5,
  couponCode: 'FRESH50',
};

export const MOCK_DELIVERY_PARTNER: DeliveryPartner = {
  id: 'dp1',
  name: 'Marcus Chen',
  avatarUrl: 'https://i.pravatar.cc/120?u=marcuschen',
  rating: 4.9,
  title: 'Your Delivery Hero',
};

export const MOCK_STORES: Store[] = [
  {
    id: 's1',
    name: 'Organic Market',
    imageUrl: mockImage('s1'),
    rating: 4.8,
    reviewCount: 1200,
    deliveryTimeMin: 12,
    deliveryTimeMax: 15,
    deliveryFee: 0,
    distanceKm: 1.2,
    categories: ['Vegetables', 'Fruits', 'Dairy & Eggs'],
    isOpen: true,
  },
  {
    id: 's2',
    name: 'Green Valley Organic',
    imageUrl: mockImage('s2'),
    rating: 4.6,
    reviewCount: 890,
    deliveryTimeMin: 15,
    deliveryTimeMax: 20,
    deliveryFee: 1.99,
    distanceKm: 2.4,
    categories: ['Vegetables', 'Snacks', 'Beverages'],
    isOpen: true,
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    storeId: 's1',
    name: 'Roma Tomatoes',
    description: 'Juicy Roma tomatoes perfect for salads and sauces.',
    imageUrl: mockImage('p1'),
    price: 4.99,
    unit: '500g',
    category: 'Vegetables',
    badge: ProductBadge.Organic,
    inStock: true,
    stockCount: 50,
    tags: ['Organic', 'Local Farm'],
  },
  {
    id: 'p2',
    storeId: 's1',
    name: 'Dutch Carrots',
    description: 'Sweet and crunchy Dutch carrots.',
    imageUrl: mockImage('p2'),
    price: 3.2,
    unit: '1 bunch',
    category: 'Vegetables',
    inStock: true,
    stockCount: 40,
  },
  {
    id: 'p3',
    storeId: 's1',
    name: 'Organic Broccoli',
    description: 'Fresh organic broccoli crowns.',
    imageUrl: mockImage('p3'),
    price: 2.1,
    originalPrice: 2.8,
    unit: 'per head',
    category: 'Vegetables',
    badge: ProductBadge.Sale,
    inStock: true,
    stockCount: 30,
  },
  {
    id: 'p4',
    storeId: 's1',
    name: 'Hass Avocado',
    description: 'Creamy Hass avocados, ripe and ready.',
    imageUrl: mockImage('p4'),
    price: 2.5,
    unit: 'each',
    category: 'Vegetables',
    inStock: true,
    stockCount: 60,
  },
  {
    id: 'p5',
    storeId: 's1',
    name: 'Red Bell Pepper',
    description: 'Vibrant red bell peppers.',
    imageUrl: mockImage('p5'),
    price: 1.99,
    unit: 'each',
    category: 'Vegetables',
    inStock: true,
    stockCount: 45,
  },
  {
    id: 'p6',
    storeId: 's1',
    name: 'Baby Spinach',
    description: 'Tender baby spinach leaves.',
    imageUrl: mockImage('p6'),
    price: 3.99,
    unit: '200g',
    category: 'Vegetables',
    badge: ProductBadge.Organic,
    inStock: true,
    stockCount: 35,
  },
  {
    id: 'p7',
    storeId: 's1',
    name: 'Sweet Corn',
    description: 'Farm-fresh sweet corn.',
    imageUrl: mockImage('p7'),
    price: 0.99,
    unit: 'each',
    category: 'Vegetables',
    inStock: true,
    stockCount: 80,
  },
  {
    id: 'p8',
    storeId: 's1',
    name: 'Portobello Mushrooms',
    description: 'Large portobello mushroom caps.',
    imageUrl: mockImage('p8'),
    price: 4.5,
    unit: '250g',
    category: 'Vegetables',
    inStock: true,
    stockCount: 25,
  },
  {
    id: 'p9',
    storeId: 's1',
    name: 'Fresh Organic Strawberries',
    description:
      'Hand-picked organic strawberries from local farms. Sweet, juicy, and packed with Vitamin C. Perfect for smoothies, desserts, or snacking.',
    imageUrl: mockImage('p9'),
    price: 6.25,
    unit: '500g Box • Sustainably Farmed',
    category: 'Fruits',
    badge: ProductBadge.Organic,
    inStock: true,
    stockCount: 20,
    pricePerKg: 12.5,
    tags: ['Organic', 'Local Farm', 'Vitamin C'],
    nutrition: { calories: '160', fiber: '4g', sugar: '12g', vitaminC: '150%' },
  },
  {
    id: 's2-p1',
    storeId: 's2',
    name: 'Farm Veggie Mix',
    description: 'Seasonal mixed vegetables.',
    imageUrl: mockImage('s2-p1'),
    price: 5.49,
    unit: '1 kg',
    category: 'Vegetables',
    badge: ProductBadge.Organic,
    inStock: true,
    stockCount: 40,
  },
  {
    id: 's2-p2',
    storeId: 's2',
    name: 'Cherry Tomatoes',
    description: 'Sweet cherry tomatoes on the vine.',
    imageUrl: mockImage('s2-p2'),
    price: 3.99,
    unit: '250g',
    category: 'Vegetables',
    inStock: true,
    stockCount: 55,
  },
  {
    id: 's2-p3',
    storeId: 's2',
    name: 'Sea Salt Potato Chips',
    description: 'Crispy kettle-cooked chips.',
    imageUrl: mockImage('s2-p3'),
    price: 2.49,
    unit: '150g',
    category: 'Snacks',
    inStock: true,
    stockCount: 70,
  },
  {
    id: 's2-p4',
    storeId: 's2',
    name: 'Trail Mix Deluxe',
    description: 'Nuts, seeds, and dried fruit.',
    imageUrl: mockImage('s2-p4'),
    price: 4.99,
    unit: '300g',
    category: 'Snacks',
    inStock: true,
    stockCount: 35,
  },
  {
    id: 's2-p5',
    storeId: 's2',
    name: 'Cold Pressed OJ',
    description: 'Fresh orange juice.',
    imageUrl: mockImage('s2-p5'),
    price: 3.29,
    unit: '1 L',
    category: 'Beverages',
    inStock: true,
    stockCount: 45,
  },
  {
    id: 's2-p6',
    storeId: 's2',
    name: 'Sparkling Lemon Water',
    description: 'Zero sugar sparkling water.',
    imageUrl: mockImage('s2-p6'),
    price: 1.99,
    unit: '500ml',
    category: 'Beverages',
    inStock: true,
    stockCount: 90,
  },
];

export const MOCK_RELATED: Product[] = [
  {
    id: 'r1',
    storeId: 's1',
    name: 'Whole Milk',
    description: 'Fresh whole milk',
    imageUrl: mockImage('r1'),
    price: 3.5,
    unit: '1L',
    category: 'Dairy & Eggs',
    inStock: true,
    stockCount: 100,
  },
  {
    id: 'r2',
    storeId: 's1',
    name: 'Organic Bananas',
    description: 'Organic bananas',
    imageUrl: mockImage('r2'),
    price: 1.2,
    unit: 'bunch',
    category: 'Fruits',
    inStock: true,
    stockCount: 90,
  },
];

export const MOCK_CART_ITEMS = [
  {
    productId: 'p1',
    product: MOCK_PRODUCTS[0]!,
    quantity: 2,
  },
  {
    productId: 'p3',
    product: MOCK_PRODUCTS[2]!,
    quantity: 1,
  },
];

export const MOCK_ADDRESS: Address = {
  id: 'a1',
  label: 'Home',
  line1: 'Premium Urban Lofts, Apt 402',
  line2: '12th Ave, Midtown Commercial District, Metropolis',
  city: 'Metropolis',
  state: 'NY',
  zipCode: '10001',
  isDefault: true,
};

const hoursAgo = (h: number) => new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
const daysAgo = (d: number) => new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();

export const MOCK_ORDERS: Order[] = [
  {
    id: 'o1',
    displayId: 'FD-8291',
    storeId: 's1',
    storeName: 'Organic Market',
    items: MOCK_CART_ITEMS,
    status: OrderStatus.OutForDelivery,
    address: MOCK_ADDRESS,
    summary: { subtotal: 42.5, deliveryFee: 0, taxes: 2.45, discount: 0, total: 42.5 },
    createdAt: hoursAgo(0.5),
    estimatedDelivery: '15-20 min',
    estimatedDeliveryWindow: '12:45 PM – 1:00 PM',
    deliveryPartner: MOCK_DELIVERY_PARTNER,
    isOnTime: true,
  },
  {
    id: 'o2',
    displayId: 'FD-8102',
    storeId: 's2',
    storeName: 'Green Valley Organic',
    items: [
      { productId: 's2-p3', product: MOCK_PRODUCTS[11]!, quantity: 2 },
      { productId: 's2-p5', product: MOCK_PRODUCTS[13]!, quantity: 1 },
    ],
    status: OrderStatus.Preparing,
    address: MOCK_ADDRESS,
    summary: { subtotal: 8.27, deliveryFee: 1.99, taxes: 0.5, discount: 0, total: 10.76 },
    createdAt: hoursAgo(1),
    estimatedDelivery: '25-30 min',
    estimatedDeliveryWindow: '1:15 PM – 1:30 PM',
    isOnTime: true,
  },
  {
    id: 'o3',
    displayId: 'FD-7988',
    storeId: 's1',
    storeName: 'Organic Market',
    items: [
      { productId: 'p9', product: MOCK_PRODUCTS[8]!, quantity: 1 },
      { productId: 'p6', product: MOCK_PRODUCTS[5]!, quantity: 2 },
    ],
    status: OrderStatus.Delivered,
    address: MOCK_ADDRESS,
    summary: { subtotal: 15.25, deliveryFee: 0, taxes: 0.75, discount: 2, total: 14 },
    createdAt: daysAgo(2),
    isOnTime: true,
  },
  {
    id: 'o4',
    displayId: 'FD-7755',
    storeId: 's1',
    storeName: 'Organic Market',
    items: [{ productId: 'p4', product: MOCK_PRODUCTS[3]!, quantity: 3 }],
    status: OrderStatus.Delivered,
    address: MOCK_ADDRESS,
    summary: { subtotal: 7.5, deliveryFee: 0, taxes: 0.38, discount: 0, total: 7.88 },
    createdAt: daysAgo(5),
    isOnTime: true,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    type: NotificationType.Order,
    title: 'Order on the way',
    body: 'Your order from Organic Market is out for delivery.',
    read: false,
    createdAt: new Date().toISOString(),
  },
];

export const MOCK_VENDOR_PRODUCTS: VendorProduct[] = MOCK_PRODUCTS.map((p, i) => ({
  ...p,
  sku: `SKU-${1000 + i}`,
  lowStockThreshold: 10,
}));

export const MOCK_DELIVERY_ASSIGNMENTS: DeliveryAssignment[] = [
  {
    id: 'd1',
    orderId: 'o1',
    storeName: 'Organic Market',
    customerAddress: 'Premium Urban Lofts, Apt 402',
    status: OrderStatus.ReadyForPickup,
    pickupConfirmed: false,
    deliveryConfirmed: false,
    earnings: 8.5,
  },
];

export const MOCK_ESSENTIALS: Product[] = [
  {
    id: 'e1',
    storeId: 's1',
    name: 'Whole Milk 1L',
    brand: 'Fresh Farm',
    description: 'Farm fresh whole milk',
    imageUrl: mockImage('e1'),
    price: 4.5,
    unit: '1L',
    category: 'Dairy',
    badge: ProductBadge.Organic,
    inStock: true,
    stockCount: 100,
  },
  {
    id: 'e2',
    storeId: 's1',
    name: 'Fresh Strawberries',
    brand: 'Berry Best',
    description: 'Sweet strawberries',
    imageUrl: mockImage('e2'),
    price: 6.25,
    unit: '250g',
    category: 'Fruits',
    inStock: true,
    stockCount: 50,
  },
  {
    id: 'e3',
    storeId: 's1',
    name: 'Organic Asparagus',
    brand: 'Green Valley',
    description: 'Organic asparagus bunch',
    imageUrl: mockImage('e3'),
    price: 5.99,
    unit: 'bunch',
    category: 'Vegetables',
    badge: ProductBadge.Organic,
    inStock: true,
    stockCount: 30,
  },
  {
    id: 'e4',
    storeId: 's1',
    name: 'Basmati Rice 2kg',
    brand: 'Golden Grain',
    description: 'Premium basmati rice',
    imageUrl: mockImage('e4'),
    price: 8.99,
    unit: '2kg',
    category: 'Staples',
    inStock: true,
    stockCount: 80,
  },
];

export const MOCK_SCANNER_PRODUCT: Product = {
  id: 'scan1',
  storeId: 's1',
  name: 'Organic Whole Milk',
  brand: 'Fresh Farm',
  description: '1 Gallon • Locally Sourced',
  imageUrl: mockImage('scan1'),
  price: 4.99,
  unit: '1 Gallon',
  category: 'Dairy',
  badge: ProductBadge.Organic,
  inStock: true,
  stockCount: 50,
};

export const delay = (ms = 400) => new Promise((r) => setTimeout(r, ms));
